### ISSUE TITLE
Can you please add a simple cinterop variant?

### ISSUE THREAD

**Issue by shalva97** [whyoleg/ffi-kotlin#3]
I wil admit, im not mart enough to understand what is going on in this project. Some parts of it is red with syntax errors, other parts are just something I have never seen.

Could you please add a very very simple example? something like this where there is one function called `greet()` in Kotlin Native
```
fun greet(): String {
    return "Hello world!"
}
```

and then it is called from JVM like this:
```
fun main() {
    println(someNativeMagicHere.greet()) // will call native function and print "Hello world!"
}
```

Will be happy to see a sample similar to it.

**Comment by whyoleg** [comment]
Hey
This repository is **BIG EXPERIMENT** and for now is used mostly for investigating possibility on how foreign functions (f.e. from C) can be called in Kotlin from different targets.

> something like this where there is one function called greet() in Kotlin Native ... and then it is called from JVM like this:

For now the idea of this project is not to provide interop between K/N and K/JVM, but to provide interop between K/* and C code.
Likely, it will be possible to make it work in future in simple way, but not in near future, as it's not a direct goal of this project.

**Comment by shalva97** [comment]
Thanks for reply. So just to confirm is it possible to have interop between K/N and K/JVM in a not too hard way, right? For example, in this projet there is so much in Gradle, probably 90% of it something I have never seen before. It would take me month to learn it...

You know it just looks cool to have a K/N code which will be called from K/JVM, I dont know why but I want to try it and then I could contribute K/N code to other projects 🚀 

I know this is off topic now, but can you provide some roadmap, what I need to research to be able to do interop between K/N and K/JVM?

**Comment by whyoleg** [comment]
Overall it's doable now.
Let's have K/N code like this:
```kotlin
package somelib.native
fun customFunction(arg: Int): Int { /*impl go here, we can also use cinterop declarations here*/ }
```
By using official tutorial you can compile and link it into a dynamic library with exported headers: https://kotlinlang.org/docs/native-dynamic-libraries.html#create-a-kotlin-library
Let's call final native library `nativeinterop`
Hey, we are done with K/N part. Now let's go to K/JVM part :)
Let's start with K/JVM code:
```kotlin
package somelib.jvm
object JNI {
  init {
    System.loadLibrary("nativeinterop")
  }
  external fun customFunction(arg: Int): Int
}
```
To call native function from K/JVM via JNI we will need to create a C file for it:
```c
#include <jni.h>
#include <libnativeinterop_api.h>

JNIEXPORT jint JNICALL Java_somelib_jvm_JNI_customFunction (JNIEnv* env, jclass jclss,
  jint arg
) {
  return libnativeinterop_symbols()->kotlin.root.somelib.native.customFunction(arg);
}
```
After this we need to compile this C file, f.e. using [task from repository](https://github.com/whyoleg/ffi-kotlin/blob/main/build-logic/src/main/kotlin/jni/BuildJni.kt). Note, you will need to provide paths to K/N library header and dynamic library. Also you will need to adapt it a little so it will be able to run on different OS (current implementation will work only for macOS), it should be rather easy, as there is a lot of information in the web on how to do this. 
Now, the last part, we need to provide native library on JVM library path. F.E by adding path to `libnativeinterop.dylib` to `LD_LIBRARY_PATH` (or any other way, f.e. one of a lot articles: https://www.chilkatsoft.com/java-loadLibrary-MacOSX.asp)

And here we go, we can use native libraries, or code written in K/N from K/JVM.
Yes, I understand, that it's not ideal, but most of those things are boilerplate and we can automate it.

Returning to project (if anyone else will read this issue)
The goal of this project is to allow to do following in all Kotlin targets:
```kotlin
@ForeignCInclude("nativelibrary/someheader.h")
@ForeignCFunction("custom_function_from_native_library")
fun customFunction(arg: Int): Int
```
Where `customFunction` declared in some native C library. Overall, the same thing, that CInterop does, but for multi-platform.
Of course there will be automated bindings generation, as well as gradle and compiler plugins which will mostly automate everything.

And only after that moment, we can try to improve interoperability between K/JVM and K/N by using all created infrastructure to write simple integration layer, so user will be able to to write only K/N and K/* code.
Though for now, it's not in near future, not even planned, as it's not really that popular use case AFAIK.

So, stay tuned!

**Comment by shalva97** [comment]
I got stuck at compiling the C file. Im getting error
```
Undefined symbols for architecture x86_64:
  "_libnativeinterop_symbols", referenced from:
      _Java_somelib_jvm_JNI_customFunction in jni-6bfe86.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FAILURE: Build failed with an exception.
```

and not sure how to fix it. any ideas? I have created repo here https://github.com/shalva97/hello-interop

**Comment by whyoleg** [comment]
Hey @shalva97, looks like repository is private

**Comment by shalva97** [comment]
my bad, I made it public

**Comment by shalva97** [comment]
okay, I have updated the project a bit, not sure if modules are defined correctly, but thats how I though it should work.

There where few errors I sort of fixed them. First was about a missing file
```
/Users/shalva/IdeaProjects/hello-interop/src/jniMain/c/jni.c:2:10: fatal error: 'libnativeinterop_api.h' file not found
#include <libnativeinterop_api.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I fixed it by manually running `linkDebugSharedMacosX64` and then added path to your task:
```kotlin
tasks.named<jni.BuildJni>("buildJni") {
    outputFilePath.set("macos-arm64/libffi-jni.dylib")
    includeDirs.add("build/bin/macosX64/debugShared")
}
```

then I had problem with JDK 20, it was trying to download it from AdoptOpen so I commented out `jvmToolchain(20)` in `buildx-multiplatform.gradle.kts`, hopefully its not important...

Next error is:
```
Undefined symbols for architecture x86_64:
  "_libnativeinterop_symbols", referenced from:
      _Java_somelib_jvm_JNI_customFunction in jni-8d9f5a.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
and I dont know how to fix it.

To run it, I have `jvm` module, there is green button, which runs `JNI.customFunction`, I expect it to return 42 and write it in console...

**Comment by whyoleg** [comment]
sorry for the delay, got a bit stuck with working on other projects...
I saw such errors a lot during development of ffi-kotlin - linker can't find symbol, most likely because path to built library is incorrect.
If everything goes well, I will create a sample GitHub project by the end of this or next week to show how it could be done

**Comment by shalva97** [comment]
Thanks, that would be great! 🚀

**Comment by whyoleg** [comment]
Hey @shalva97!
I've prepared a little sample with minimal amount of gradle magic here: https://github.com/whyoleg/kotlin-interop-playground/tree/main/native-to-jvm
Should work out of the box.

**Comment by whyoleg** [comment]
I will close this issue now. For help with K/N to K/JVM interop, please create issues in other repository. I will try to help, if I would have time
